### ISSUE TITLE
Search should be sortable by the number of uses

### ISSUE THREAD

**Issue by djskelton** [SynBioHub/synbiohub#404]
Searching for "GFP" in the search box on the home page yields no / few results that are just the GFP coding sequence (because of a lot of noise in the iGEM dataset); perhaps having search sortable by number of uses may allow a user to find the GFP CDS?

**Comment by cjmyers** [comment]
Agreed, but will take a bit of work.

**Comment by zachzundel** [comment]
@cjmyers How do we calculate the number of uses?

**Comment by cjmyers** [comment]
Number of times URI of top level appears in object of a triple.  Will require some spraql magic

Chris

**Comment by zachzundel** [comment]
Updated `search.sparql` to do this

**Comment by cjmyers** [comment]
I had to revert this one.  It broke a ton of searches.  For example, it broke "submissions" viewing.  The problem is likely due to the fact that Collections have not uses.

**Comment by zachzundel** [comment]
Fixed this and updated

**Comment by cjmyers** [comment]
I'm still not sure this is working.  There is no longer any Count, and ?uses appears to be unbound to anything.

**Comment by zachzundel** [comment]
Okay, I re-added the `COUNT` and `?uses` is bound to its result.

**Comment by cjmyers** [comment]
This turns out to be too slow with the approach we took in search.sparql.  Need to debug this.
