### ISSUE TITLE
Problems uploading zip file with sub-structure

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#602]
When a zip file has sub-structure (directories) the files are not uploaded.  Should recurse the file tree in the zip file and upload all files found.

**Comment by zachzundel** [comment]
Done and ready for more testing

**Comment by cjmyers** [comment]
This is still not working for me.  Try this example:

[Split Recombinases for Addgene.zip](https://github.com/SynBioHub/synbiohub/files/1877429/Split.Recombinases.for.Addgene.zip)

**Comment by zachzundel** [comment]
Sorry, forgot to push the relevant code. I've done so now.

**Comment by cjmyers** [comment]
Had a merge conflict, so I accidentally undid your changes, but I think I restored them.  This seems to work now.  Maintaining sub-structure in collections would still be good, so will move the version and leave this open.

**Comment by cjmyers** [comment]
Separare issue for sub-structure collections.
